CREATE TABLE teams
(
    id      SERIAL PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    user_id INTEGER      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    cave_id INTEGER      REFERENCES dragon_cave (id) ON DELETE SET NULL

);

ALTER TABLE person ADD COLUMN team_id INTEGER REFERENCES teams (id) ON DELETE SET NULL;